# Generated by Django 5.1.6 on 2025-04-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatorapp', '0004_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otp',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
