# Generated by Django 5.1.6 on 2025-04-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticatorapp', '0005_otp_attempts_otp_last_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='last_sent',
        ),
    ]
