# Generated by Django 5.1.6 on 2025-03-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
